//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Championnat_Foot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class But
    {
        public int codematch { get; set; }
        public int codejou { get; set; }
        public int minute { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual Match Match { get; set; }
    }
}
