//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Championnat_Foot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrainer
    {
        public string nomeq { get; set; }
        public string codesai { get; set; }
        public int codeent { get; set; }
    
        public virtual Entraineur Entraineur { get; set; }
        public virtual Equipe Equipe { get; set; }
        public virtual Saison Saison { get; set; }
    }
}
