//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Championnat_Foot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journee
    {
        public int NumJour { get; set; }
        public string CodeSai { get; set; }
        public System.DateTime Date_Debut { get; set; }
        public System.DateTime Date_Fin { get; set; }
        public string Detail { get; set; }
    
        public virtual Saison Saison { get; set; }
    }
}
