//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Championnat_Foot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Arbitrages = new HashSet<Arbitrage>();
            this.Buts = new HashSet<But>();
            this.Remplacements = new HashSet<Remplacement>();
            this.Joueurs = new HashSet<Joueur>();
        }
    
        public int codeMatch { get; set; }
        public string NomEqDom { get; set; }
        public string NomEqVis { get; set; }
        public string nomStd { get; set; }
        public System.DateTime DateMatch { get; set; }
        public int Attendence { get; set; }
        public int Temperature { get; set; }
        public int Humidite { get; set; }
        public int ButDom { get; set; }
        public int ButVis { get; set; }
        public string TypeMatch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arbitrage> Arbitrages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<But> Buts { get; set; }
        public virtual Equipe Equipe { get; set; }
        public virtual Equipe Equipe1 { get; set; }
        public virtual Stade Stade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remplacement> Remplacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Joueur> Joueurs { get; set; }
    }
}
