//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Championnat_Foot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stade()
        {
            this.Matchs = new HashSet<Match>();
        }
    
        public string NomStd { get; set; }
        public int Capacite { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Peleuse { get; set; }
        public int Largeur { get; set; }
        public int Longueur { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matchs { get; set; }
    }
}
